"""initial schema: users, expense_reports, expense_lines, report_approvers,
status_events, comments, alert_dismissals

Hand-written rather than autogenerated: at the time this was authored no live Postgres
instance was reachable yet, so this mirrors app/models/*.py exactly instead of being
diffed from a running database. It has since been verified against a real local
Postgres 16 container - upgrade, downgrade to base, and re-upgrade all succeed, and
\d confirms the tables, enum types, and the reject-requires-reason check constraint
land as designed.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-30
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

ROLE_VALUES = ["employee", "approver"]
REPORT_STATUS_VALUES = ["draft", "submitted", "approved", "rejected", "paid"]
EXPENSE_CATEGORY_VALUES = ["travel", "meals", "lodging", "supplies", "software", "other"]


def upgrade() -> None:
    bind = op.get_bind()

    role_enum = postgresql.ENUM(*ROLE_VALUES, name="role")
    report_status_enum = postgresql.ENUM(*REPORT_STATUS_VALUES, name="report_status")
    expense_category_enum = postgresql.ENUM(*EXPENSE_CATEGORY_VALUES, name="expense_category")
    role_enum.create(bind, checkfirst=True)
    report_status_enum.create(bind, checkfirst=True)
    expense_category_enum.create(bind, checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column(
            "role", postgresql.ENUM(*ROLE_VALUES, name="role", create_type=False), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "expense_reports",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(*REPORT_STATUS_VALUES, name="report_status", create_type=False),
            nullable=False,
            server_default="draft",
        ),
        sa.Column("total_cents", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_reports_owner_id", "expense_reports", ["owner_id"])
    op.create_index("ix_reports_status", "expense_reports", ["status"])
    op.create_index("ix_reports_archived_at", "expense_reports", ["archived_at"])

    op.create_table(
        "expense_lines",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "report_id",
            sa.Integer(),
            sa.ForeignKey("expense_reports.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM(*EXPENSE_CATEGORY_VALUES, name="expense_category", create_type=False),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_lines_report_id", "expense_lines", ["report_id"])

    op.create_table(
        "report_approvers",
        sa.Column(
            "report_id",
            sa.Integer(),
            sa.ForeignKey("expense_reports.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("approver_id", sa.Integer(), sa.ForeignKey("users.id"), primary_key=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_report_approvers_approver_id", "report_approvers", ["approver_id"])

    op.create_table(
        "status_events",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "report_id",
            sa.Integer(),
            sa.ForeignKey("expense_reports.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "from_status",
            postgresql.ENUM(*REPORT_STATUS_VALUES, name="report_status", create_type=False),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            postgresql.ENUM(*REPORT_STATUS_VALUES, name="report_status", create_type=False),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "to_status != 'rejected' OR reason IS NOT NULL",
            name="ck_status_events_reject_requires_reason",
        ),
    )
    op.create_index("ix_status_events_report_id", "status_events", ["report_id"])

    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "report_id",
            sa.Integer(),
            sa.ForeignKey("expense_reports.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("author_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_comments_report_id", "comments", ["report_id"])

    op.create_table(
        "alert_dismissals",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "report_id",
            sa.Integer(),
            sa.ForeignKey("expense_reports.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("approver_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("dismissed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("snoozed_until", sa.DateTime(), nullable=False),
        sa.UniqueConstraint(
            "report_id", "approver_id", name="uq_alert_dismissals_report_approver"
        ),
    )
    op.create_index("ix_alert_dismissals_report_id", "alert_dismissals", ["report_id"])


def downgrade() -> None:
    op.drop_table("alert_dismissals")
    op.drop_table("comments")
    op.drop_table("status_events")
    op.drop_table("report_approvers")
    op.drop_table("expense_lines")
    op.drop_table("expense_reports")
    op.drop_table("users")

    bind = op.get_bind()
    postgresql.ENUM(name="expense_category").drop(bind, checkfirst=True)
    postgresql.ENUM(name="report_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="role").drop(bind, checkfirst=True)
